### PR TITLE
Remove AsyncTask

### PR DESCRIPTION
**Pull request by legendecas**
We can revisit AsyncTask after the AsyncLocal is accepted.

### CODE REVIEW

**Comment by jridgewell** [comment]
I had created `AsyncContext.Snapshot`, which is essentially the same as the `AsyncTask`, because it seems necessary. It even closely mirrors the new `console.createTask` API [introduced by Chrome](https://developer.chrome.com/blog/devtools-modern-web-debugging/#linked-stack-traces).

**Comment by legendecas** [comment]
Yeah, the tasking API is important for frameworks or libraries to coordinate their scheduling with the async context propagation (and the async stack tagging). 

Still, I believe it can be helpful if we can find a _minimum subset_ of the proposal that can resolve the crux of the problem: i.e. async context propagation. That's why I think we can defer the `AsyncTask` API to a later point. However, this doesn't mean we are not going to consider this API. Hosts like browsers should still be able to facilitate a low-level definition to integrate web APIs into the async context propagation, e.g. `setTimeout` and many others.

Without the `AsyncTask` API, we can still use built-ins to coordinate the scheduling with the async context propagation. Like, with a minor modification on the example in the `console.createTask` document, we can propagate async contexts with built-in `Promise`:

```js
const { AsyncLocalStorage } = require('async_hooks');

function makeDeferred() {
  let resolve, reject;
  const promise = new Promise((res, rej) => {
    resolve = res;
    reject = rej;
  });
  return { resolve, reject, promise };
}

function makeScheduler() {
  const tasks = [];

  return {
    schedule(f) {
      const deferred = makeDeferred();
      deferred.promise.then(f);
      tasks.push({ deferred });
    },

    work() {
      while (tasks.length) {
        const { deferred } = tasks.shift();
        // not identical to `f()`
        deferred.resolve();
      }
    },
  };
}

const scheduler = makeScheduler();
const asyncLocal = new AsyncLocalStorage();

function loop() {
  scheduler.work();
  setImmediate(loop);
};

loop();

asyncLocal.run(1, () => {
  scheduler.schedule(() => {
    console.log('expect 1:', asyncLocal.getStore());
  });
});
asyncLocal.run(2, () => {
  scheduler.schedule(() => {
    console.log('expect 2:', asyncLocal.getStore());
  });
});
```

**Review by jridgewell — APPROVED** [review]
The real problem with the fallback of using promises to capture the trace is that all possible callbacks must be registered immediately, they can't be deferred to a later time. But, I think this is OK if we're trying for a minimal API.

**Comment by legendecas** [comment]
Yeah, capturing the context with promise must be performed in the context of the initiating call stack. Also, the evaluation of `f()` in the queue is re-scheduled with platform task queues. They are not essentially identical.

I'm going to open an issue to track the revisit of `AsyncTask` and merge this.

**Pull request merged**
